In [34]:
# %load gen_kfold.py

"""
__file__

    gen_kfold.py

__description__

    This file generates the StratifiedKFold indices which will be kept fixed in
    ALL the following model building parts.

__author__

    Chenglong Chen < c.chenglong@gmail.com >

"""

import sys
import dill
from sklearn.model_selection import StratifiedKFold
sys.path.append("../")
from param_config import config
import numpy as np

In [4]:
## load data
with open(config.processed_train_data_path, "rb") as f:
    dfTrain = dill.load(f)

In [7]:
list(zip(["relevance", "query"], ["median_relevance", "qid"]))

[('relevance', 'median_relevance'), ('query', 'qid')]

In [40]:
skf = [0]*config.n_runs
for stratified_label,key in zip(["relevance", "query"], ["median_relevance", "qid"]):
    for run in range(config.n_runs):
        random_seed = 2015 + 1000 * (run+1)
#         skf[run] = StratifiedKFold(dfTrain[key], n_folds=config.n_folds,
#                                     shuffle=True, random_state=random_seed)
#         skf[run] = StratifiedKFold(n_splits=config.n_folds,shuffle=True, random_state=random_seed)
#         s.split(dfTrain[stratified_label],dfTrain[key])
        s = StratifiedKFold(n_splits=config.n_folds,shuffle=True, random_state=random_seed)
        l = []
        fold = 0
        for validInd, trainInd in s.split(np.arange(dfTrain.shape[0]),np.ones(dfTrain.shape[0])):
            print("================================")
            print("Index for run: %s, fold: %s" % (run+1, fold+1))
            print("Train (num = %s)" % len(trainInd))
            print(trainInd[:10])
            print("Valid (num = %s)" % len(validInd))
            print(validInd[:10])
            fold += 1
            l.append((validInd, trainInd))        
        skf[run]=l
    with open("%s/stratifiedKFold.%s1.pkl" % (config.data_folder, stratified_label), "wb") as f:
        dill.dump(skf, f)

Index for run: 1, fold: 1
Train (num = 3386)
[ 2  5  9 12 14 20 21 22 23 28]
Valid (num = 6772)
[ 0  1  3  4  6  7  8 10 11 13]
Index for run: 1, fold: 2
Train (num = 3386)
[ 0  1  3  6  8 13 15 16 18 24]
Valid (num = 6772)
[ 2  4  5  7  9 10 11 12 14 17]
Index for run: 1, fold: 3
Train (num = 3386)
[ 4  7 10 11 17 19 25 29 34 35]
Valid (num = 6772)
[ 0  1  2  3  5  6  8  9 12 13]
Index for run: 2, fold: 1
Train (num = 3386)
[ 0  2  4 12 17 18 22 28 32 33]
Valid (num = 6772)
[ 1  3  5  6  7  8  9 10 11 13]
Index for run: 2, fold: 2
Train (num = 3386)
[ 1  5  6  7  8  9 10 11 13 14]
Valid (num = 6772)
[ 0  2  3  4 12 15 16 17 18 22]
Index for run: 2, fold: 3
Train (num = 3386)
[ 3 15 16 24 26 27 31 34 35 40]
Valid (num = 6772)
[ 0  1  2  4  5  6  7  8  9 10]
Index for run: 3, fold: 1
Train (num = 3386)
[ 0  2  7 12 14 17 19 23 24 25]
Valid (num = 6772)
[ 1  3  4  5  6  8  9 10 11 13]
Index for run: 3, fold: 2
Train (num = 3386)
[ 1  3  9 10 11 16 18 20 30 31]
Valid (num = 6772)
[ 0  2  